### ISSUE TITLE
distributed train, what should I do?

### ISSUE THREAD

**Issue by Scout-UCAS** [Z-Zheng/FarSeg#1]
subprocess.CalledProcessError: Command '['/home/ps/anaconda3/envs/farseg/bin/python', '-u', 'apex_train.py', '--local_rank=1', '--config_path=configs.isaid.farseg50', '--model_dir=./log/isaid_segm/farseg50', '--opt_level=O']' returned non-zero exit status 1.

**Comment by Scout-UCAS** [comment]
solved

**Comment by bardisafa** [comment]
Hi,

I also get the similar error. Could you please elaborate on how you solved the issue.
