### ISSUE TITLE
关于论文中的相关问题请教

### ISSUE THREAD

**Issue by slacklife** [Z-Zheng/FarSeg#2]
您好，读了您的论文非常受教，但是还有几个问题没看明白，想专门请教下：

1. 在 ``Scale-aware projection for scene embedding`` 这个章节
（1）projection functions 是用来做维度对齐，那么在 这个模块，去掉 \eta function，那么维度如何对齐呢？
（2）在这个小节的结论中，``With F-A optimization, the gain in mIoU from scale-aware projection is larger. It indicates that geospatial scene representation is related to scale and foregrounds.`` 为什么 这个 loss 上的 optimization 模块 可以 体现 geospatial scene representation 与 scale and foregrounds 相关的呢？

2.  文中的 foreground-relative contexts 和 geospatial scene-relevant context 和 图3 的  "relevant context features" 三者是否是同一个指代？这个 context 具体是指什么，它有公式表示或者具体作图表示么？

3.  在 segmentation 的时候，focal loss 需要 norm 而 检测的时候不需要呢？关于梯度消失的角度进行解释，easy 样本 梯度消失应该不影响训练吧，所以这个梯度消失为什么会影响效果？

**Comment by Z-Zheng** [comment]
感谢对我们工作的关注，下面是对您问题的一个简单回复，
1.1 w/o scale-aware proj. 指的是在不同金字塔层级共享这个proj conv. 因此仍然可以对齐
1.2 抱歉带来误解，在此解释，第二句话是对整段讨论的总结；第一句话是对实验现象的描述；

2. 是的，这里的context特指context features. 暂无
3. 这里是一个经验性发现，主要原因还是可能因为前景占比过少导致的；easy example确实不是很影响，主要是前景像素对有效梯度贡献太少，导致性能的极具下降。可能有更好的角度去解释这个问题，如果您有好的见解也可以进一步交流。

--------------
最好通过邮件的方式联系我，因为Github我不会及时看到消息，
祝好
