### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by abhigoku10** [Z-Zheng/FarSeg#3]
@Z-Zheng  thanks for open-sourcing the code base, which code to use to save the segmentation data on the original image with different color schema and class names 

Thanks in advance

**Comment by Z-Zheng** [comment]
We don't provide the visualization code.
You can simply use alpha blending to put the segmentation mask on the image.
The color map can be found at https://github.com/Z-Zheng/FarSeg/blob/003aaca75db873becdd5ca84450c9d5cfcf7901e/data/isaid.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L26
